//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18408
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordZipMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordZipMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Execute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonExecuteText {
            get {
                return ResourceManager.GetString("ButtonExecuteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonSelectInputFile {
            get {
                return ResourceManager.GetString("ButtonSelectInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alphabet (Lower) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KindOfCharctorLower {
            get {
                return ResourceManager.GetString("KindOfCharctorLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KindOfCharctorNumber {
            get {
                return ResourceManager.GetString("KindOfCharctorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Symbol に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KindOfCharctorSymbol {
            get {
                return ResourceManager.GetString("KindOfCharctorSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alphabet (Upper) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KindOfCharctorUpper {
            get {
                return ResourceManager.GetString("KindOfCharctorUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Length に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelLength {
            get {
                return ResourceManager.GetString("LabelLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelMadePassword {
            get {
                return ResourceManager.GetString("LabelMadePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password Settngs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelPasswordSettingArea {
            get {
                return ResourceManager.GetString("LabelPasswordSettingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelResult {
            get {
                return ResourceManager.GetString("LabelResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelZipDestination {
            get {
                return ResourceManager.GetString("LabelZipDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zip Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelZipSettingArea {
            get {
                return ResourceManager.GetString("LabelZipSettingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelZipSource {
            get {
                return ResourceManager.GetString("LabelZipSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Passwor Zip Maker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
